// <auto-generated />
namespace DevConVT.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmailRegisteradded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailRegisteradded));
        
        string IMigrationMetadata.Id
        {
            get { return "202109171640536_EmailRegister added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
